---
schema: armada/Chart/v1
data:
  chart_name: ingress
  values:
    monitoring:
      prometheus:
        enabled: true
        ingress_exporter:
          scrape: true
        config:
          worker-processes: "8"
    config:
      worker-processes: "8"
---
schema: armada/Chart/v1
data:
  chart_name: horizon
  values:
    conf:
      horizon:
        local_settings:
          config:
            openstack_neutron_network:
              enable_router: qqqTrueqqq
              enable_quotas: qqqTrueqqq
              enable_ipv6: qqqFalseqqq
              enable_distributed_router: qqqFalseqqq
              enable_ha_router: qqqTrueqqq
              enable_lb: qqqTrueqqq
              enable_firewall: qqqFalseqqq
              enable_vpn: qqqFalseqqq
              enable_fip_topology_check: qqqTrueqqq
---
schema: armada/Chart/v1
data:
  chart_name: mariadb
  values:
    volume:
      enabled: true
    monitoring:
      prometheus:
        enabled: true
        mysqld_exporter:
          scrape: true
---
schema: armada/Chart/v1
data:
  chart_name: rabbitmq
  values:
    monitoring:
      prometheus:
        enabled: true
        rabbitmq_exporter:
          scrape: true
---
schema: armada/Chart/v1
data:
  chart_name: memcached
  values:
    monitoring:
      prometheus:
        enabled: true
        memcached_exporter:
          scrape: true
---
schema: armada/Chart/v1
data:
  chart_name: libvirt
  values:
    network:
      backend:
        - openvswitch
    conf:
      ceph:
        enabled: true

# [glace] Reviewed by Robert #
---
schema: armada/Chart/v1
data:
  chart_name: glance
  values:
    conf:
      ceph:
        enabled: true
      glance:
        glance_store:
          rbd_store_user: glance
          rbd_store_pool: images-test
    bootstrap:
      enabled: true
# End of reviewed part #
---
schema: armada/Chart/v1
data:
  chart_name: nova
  values:
    network:
      backend:
        - openvswitch
      novncproxy:
        node_port:
          enabled: true
    conf:
      hypervisor:
        host_interface: eth0
      libvirt:
        live_migration_interface: eth0
      ceph:
        enabled: true
---
schema: armada/Chart/v1
data:
  chart_name: neutron
  values:
    network:
      backend:
        - openvswitch
      auto_bridge_add:
        br-ex: eth1
      interface:
        tunnel: eth0
    conf:
      neutron:
        DEFAULT:
          global_physnet_mtu: 1500
          service_plugins: router
      plugins:
        ml2_conf:
          ml2:
            mechanism_drivers: openvswitch,l2population
            type_drivers: flat, vxlan
            tenant_network_types: vxlan
          ml2_type_flat:
            flat_networks: external
          ml2_type_vlan:
            network_vlan_ranges: ""
        openvswitch_agent:
          ovs:
            bridge_mappings: "external:br-ex"
        linuxbridge_agent:
          linux_bridge:
            physical_interface_mappings: ""
    manifests:
      daemonset_lb_agent: false
      daemonset_ovs_agent: true
---
schema: armada/Chart/v1
data:
  chart_name: cinder
  values:
    conf:
      ceph:
        enabled: true
      cinder:
        DEFAULT:
          backup_ceph_pool: "backups-test"
          backup_ceph_user: "cinder-backup"
      backends:
        rbd1:
          rbd_pool: "volumes-test"
          rbd_secret_uuid: "582393ff-9a5c-4a2e-ae0d-86ec18c36afc"
---
schema: armada/Chart/v1
data:
  chart_name: ldap
  values:
    storage:
      pvc:
        enabled: true
---
schema: armada/Chart/v1
data:
  chart_name: elasticsearch
  values:
    conf:
      elasticsearch:
        env:  
          java_opts: "-Xms4096m -Xmx4096m"
    monitoring:
      prometheus:
        enabled: true
    storage:
      enabled: true
      requests:
        storage: 2000Gi
---
schema: armada/Chart/v1
data:
  chart_name: prometheus
  values:
    storage:
      enabled: true
      requests:
        storage: 500Gi
    conf:
      prometheus:
        command_line_flags:
          storage.tsdb.retention: 30d
---
schema: armada/Manifest/v1
metadata:
  schema: metadata/Document/v1
  name: ha-manifest
data:
  release_prefix: ha
  chart_groups:
    - openstack-infra
    - openstack-services
    - logging-infra
    - monitoring-infra
