- name: Check ssl directory
  shell: |
    dirname {{ keycloak_certificate }}
  register: keycloak_cert_dir

- name: Check keycloak certificate
  shell: |
    test -f {{ keycloak_certificate }} -a -f {{ keycloak_certificate_key }}
  register: check_keycloak_cert
  ignore_errors: yes

- name: create ssl directory
  file:
    path: "{{ keycloak_cert_dir.stdout }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  ignore_errors: yes
  when: check_keycloak_cert.rc == 1

- name: generate a Self Signed OpenSSL certificate for Keycloak
  shell: |
    openssl req -new -nodes -x509 -subj '/O=IT/CN={{ keycloak_domain }}' -days 3650 -keyout {{ keycloak_certificate_key }} -out {{ keycloak_certificate }}
  when:
    - check_keycloak_cert.rc == 1
