---
- name: Check that keycloak.yaml in inventory folder.
  stat: 
    path: "{{ inventory_dir }}/keycloak.yaml"
  register: stat_result

- name: copy keycloak.yaml to inventory folder.
  template:
    src: keycloak.yaml.j2
    dest: "{{ inventory_dir }}/keycloak.yaml"
  when: not stat_result.stat.exists

- name: install keycloak chart
  shell: |
    {{ bin_dir }}/helm upgrade --install keycloak {{ playbook_dir }}/charts/taco-helm/keycloak --namespace keycloak --values {{ inventory_dir }}/keycloak.yaml

- include_tasks: create-certificate.yml
  when:
    - keycloak_certificate is undefined
    - keycloak_certificate_key is undefined

- name: add secret for ingress
  shell: |
    {{ bin_dir }}/kubectl delete secret tls-keycloak -n {{ keycloak_namespace }}
  ignore_errors: yes

- name: add secret for ingress
  shell: |
    {{ bin_dir }}/kubectl create secret tls tls-keycloak --key {{ keycloak_certificate_key }} --cert {{ keycloak_certificate }} -n {{ keycloak_namespace }}
