istio_enabled: false
istio_injection_namespaces: ["default"]
# cluster_name: This value is defined in kubespray.

# Dirs
bin_dir: /usr/local/bin

# Versions
istio_version: "1.6.2"
jaeger_version: "1.16"
kiali_version: "v1.18"
prometheus_version: "v2.15.1"

# istioctl binary
istioctl_binary_name: "istioctl"
istioctl_binary_repo_url: "https://github.com/istio/istio/releases/download/{{ istio_version }}"
image_arch: "{{host_architecture | default('amd64')}}"
istioctl_download_url: "{{ istioctl_binary_repo_url }}/istio-{{ istio_version }}-linux-{{ image_arch }}.tar.gz"
istioctl_download_dest: "/tmp/istio-{{ istio_version }}-linux-{{ image_arch }}.tar.gz"

# images repo
docker_image_repo: "docker.io"
quay_image_repo: "quay.io"

kiali_port: 32101
jaeger_port: 32102
