---
- name: fetch mon hosts from {{ cluster }}.conf
  shell: >-
    grep 'mon host' /etc/ceph/{{ cluster }}.conf | awk '{print $4}'
  register: mon
  when: not (ceph_monitors|length > 0)

- name: set fact mon_host for armada-manifest.yml
  set_fact:
    mon_host: "{{ mon.stdout }}"
  when: mon.changed and mon.stdout != ""

- name: set fact mon_host for armada-manifest.yml
  set_fact:
    mon_host: "{{ ceph_monitors }}"
  when: (ceph_monitors|length > 0)

- name: failed to get ceph mon hosts
  fail:
    msg: "failed to get ceph mon hosts neither from vars nor {{ cluster }}.conf"
  when: not (mon_host|length > 0)

- name: set fact for rbd storageclass
  set_fact:
    rbd_provisioner_monitors: "{{ mon_host }}"

- name: fetch admin keyring from {{ cluster }}.client.admin.keyring
  shell: >-
    grep key /etc/ceph/{{ cluster }}.client.admin.keyring | awk '{print $3}' | xargs echo -n
  register: keyring
  when: not (ceph_admin_keyring|length > 0)

- name: set fact ceph_admin_keyring for armada-manifest.yml
  set_fact:
    admin_keyring: "{{ keyring.stdout }}"
  when: keyring.changed and keyring.stdout != ""

- name: set fact ceph_admin_keyring for armada-manifest.yml
  set_fact:
    admin_keyring: "{{ ceph_admin_keyring }}"
  when: (ceph_admin_keyring|length > 0)

- name: failed to get ceph admin keyring
  fail:
    msg: "failed to get admin keyring neither from vars nor /etc/ceph"
  when: not (admin_keyring|length > 0)

- name: rpm check requests
  shell: rpm -qa | grep requests
  register: check_result
  ignore_errors: true
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: reinstall python-requests if requests installed with dist package
  pip:
    name: requests
    executable: pip3
    extra_args: --ignore-installed
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - check_result.rc == 0
