---
- name: copy helm2 binary to ansible host
  fetch:
    src: "{{ bin_dir }}/helm"
    dest: "{{ artifacts_dir }}/helm2"
    flat: yes
    validate_checksum: no
  become: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: copy helm2 to bin_dir
  copy:
    src: "{{ artifacts_dir }}/helm2"
    dest: "{{ bin_dir }}/helm2"
    mode: 0755

# install helm v2tov3 plugin 
- name: check helm configuration directory
  stat:
    path: "{{ lookup('env','HOME') }}/.helm"
  become: no
  register: check_dir
  when:
    - inventory_hostname in groups['admin-node']

- name: helmv2 init with clien only
  shell: "{{ bin_dir }}/helm2 init --client-only --skip-refresh"
  become: no
  when:
    - inventory_hostname in groups['admin-node']
    - check_dir.stat.exists == false

- name: install helm2to3 plugin
  shell: "{{ bin_dir }}/helm2 plugin install https://github.com/helm/helm-2to3"
  become: no
  ignore_errors: True
  when:
    - inventory_hostname in groups['admin-node']
