---

- name: yum install packages required for mariadb
  yum:
    name: "{{ item }}" 
    state: present
  loop:
    - mariadb
    - mariadb-server
    - python2-PyMySQL
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: apt install packages required for mariadb
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - python-pymysql
  when: ansible_distribution in ["Ubuntu","Debian"]

- name: ensures /etc/my.cnf.d directory exists
  file: path=/etc/my.cnf.d state=directory

- name: copy mariadb configuration file
  template:
    src: "mariadb_ironic.cnf.j2"
    dest: "/etc/my.cnf.d/ironic.cnf"

- name: ensure started mariadb service
  systemd:
    name: mariadb
    state: started
    enabled: yes
  register: check_installed_mariadb

- name: "wait for mariadb"
  wait_for:
    port: 3306
    delay: 5
  when: check_installed_mariadb | bool == 'true'

- name: Ensure ironic user is present on all hosts.
  mysql_user:
    name: "ironic"
    password: "password"
    priv: '*.*:ALL,GRANT'
    state: present
