---
- name: Prerequisites
  include: pre-install.yml

- name: Install RabbitMQ Service
  include: install-rabbitmq.yml

- name: Install MariaDB Service
  include: install-mariadb.yml

- name: Install ISC DHCP Service
  include: install-dhcp.yml

- name: Setup TFTP Service
  include: setup-tftp.yml

- name: Install IRONIC Standalone
  include: install-ironic.yml

- name: Setup Client
  include: setup-client.yml
