---
- name: Include OS Family Specific Defaults
  include_vars: "{{ item }}"
  with_first_found:
    - "../defaults/required_defaults_{{ ansible_os_family }}_family.yml"
    - "../defaults/dummy-defaults.yml"

- name: Install Packages
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  with_items: "{{ required_packages }}"

- name: Prerequisites
  include: pre-install.yml

- name: Install RabbitMQ Service
  include: install-rabbitmq.yml

- name: Install MariaDB Service
  include: install-mariadb.yml

- name: Install ISC DHCP Service
  include: install-dhcp.yml

- name: Setup TFTP Service
  include: setup-tftp.yml

- name: Install IRONIC Standalone
  include: install-ironic.yml

- name: Setup Client
  include: setup-client.yml
