---

# do not skip this task on centos even though it doesn't use /tftpboot
# otherwise ironic conductor service cannot start
- name: create tftpboot directory
  file:
    path: "{{ item }}"
    state: directory
    owner: ironic
    group: ironic
    mode: 0777
  with_items:
    - /tftpboot

- name: yum install packages required for tftp service
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - tftp-server
    - syslinux-tftpboot
    - xinetd
    - syslinux
  when: ansible_distribution in ["CentOS","RedHat"]

- name: apt install packages required for ironic standalone
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - xinetd
    - tftpd-hpa
    - syslinux-common
    - pxelinux
  when: ansible_distribution in ["Ubuntu","Debian"]

- name: edit tftp configuration file
  template:
    src: "tftp.j2"
    dest: "/etc/xinetd.d/tftp"


- name: ensure disabled tftp service
  service:
    name: tftp
    state: stopped
    enabled: no
  when: ansible_distribution in ["CentOS","RedHat"]

- name: ensure disabled tftp service
  service:
    name: tftpd-hpa
    state: stopped
    enabled: no
  when: ansible_distribution in ["Ubuntu","Debian"]

- name: restart ironic services
  systemd:
    name: xinetd
    state: restarted

- name: copy required files to tftpboot directory
  block:
  - name: copy pxe image file to tftpboot directory
    copy:
      src: /usr/share/syslinux/pxelinux.0
      dest: /var/lib/tftpboot
      remote_src: true

  - name: copy netboot system file to tftpboot directory
    copy:
      src: /usr/share/syslinux/chain.c32
      dest: /var/lib/tftpboot
      remote_src: true
  when: ansible_distribution in ["CentOS","RedHat"]

- name: copy map-file
  template:
    src: "map-file.j2"
    dest: "{{ tftp_path }}/map-file"

- name: ensure permission and owner of tftpboot directory
  file:
    path: "{{ tftp_path }}"
    state: directory
    owner: ironic
    group: ironic
    mode: 0777
    recurse: yes
