---

- name: install ironicclient
  pip:
    name: "{{ item }}"
  with_items:
    - python-ironicclient==2.7.0
    - decorator==4.4.0
    - oslo.config==6.8.1

- name: create scripts directory
  file:
    path: "{{ lookup('env','HOME') }}/scripts"
    state: directory
  become: no

- name: copy ironic utility shell files
  copy:
    src: "{{ item }}"
    dest: "{{ lookup('env','HOME') }}/scripts"
    mode: 0775
  with_items:
    - centos-user-image-update.sh
    - real-ubuntu-deploy.sh
    - create-configdrive-file.sh
  become: no

- name: copy sample configdrive file into scripts directory
  copy:
    src: sample_configdrive.tar
    dest: "{{ lookup('env','HOME') }}/scripts"
  become: no

- name: copy ironicrc into scripts directory
  template:
    src: "ironicrc.j2"
    dest: "{{ lookup('env','HOME') }}/scripts/ironicrc"
  become: no
