# ceph
ceph_monitors: 192.168.54.21
ceph_admin_keyring: AQCqEUVY3RvrBRAABmhtxK2MvD/whiiVZ5Jkww==
taco_storage: none
local_yum_repo_enabled: false

kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
