# ceph
ceph_monitors: 10.10.40.52
ceph_admin_keyring: AQBAHAdfHQ5RLhAAzynxAYUokA55ku4ZwqVJjQ==
taco_storage_backend: none

# istio
download_istio_images: true

kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18

openstack_manifest_path: "{{ inventory_dir }}/openstack-manifest.yaml"
