# tacoplay
container_registry_enabled: true
#docker_insecure_registries: ["castera-admin:5000"]
#taco_apps: ["openstack", "lma", "sona"]
#taco_apps: ["openstack", "sona"]
taco_apps: ["openstack"]

# container registry
registry_volume_archived: false
container_registry_volume: "/DATA/docker_registry"
container_registry_volume_archive: "{{ inventory_dir }}/docker_registry.tar.gz"
container_registry_volume_dir: "{{ playbook_dir }}/docker_registry"

# ceph
### FIXME ###
monitor_interface: ens5
public_network: 192.168.201.0/24,192.168.202.0/24
cluster_network: 192.168.201.0/24,192.168.202.0/24

ceph_conf_overrides:
      global:
        mon_allow_pool_delete: true
        mon_osd_down_out_subtree_limit: host
        osd_pool_default_size: 3
        osd_pool_default_min_size: 2
        osd_pg_stat_report_internal_max: 1
      osd:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
        osd_pg_log_dups_tracked: 10
        osd_pg_log_trim_min: 10

lvm_volumes:
  - data: /dev/vdb
######

openstack_config: true
kube_pool:
  name: "kube"
  pg_num: 8
  pgp_num: 8
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
openstack_glance_pool:
  name: "images"
  pg_num: 8
  pgp_num: 8
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
openstack_cinder_pool:
  name: "volumes"
  pg_num: 8
  pgp_num: 8
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
openstack_cinder_backup_pool:
  name: "backups"
  pg_num: 8
  pgp_num: 8
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
openstack_nova_vms_pool:
  name: "vms"
  pg_num: 8
  pgp_num: 8
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"

openstack_pools:
  - "{{ kube_pool }}"
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_pool }}"
  - "{{ openstack_cinder_backup_pool }}"
  - "{{ openstack_nova_vms_pool }}"

# k8s
### FIXME
ipip_mode: Always
os_root_user: admin
os_root_password: password
