---
- name: check if {{ armada_manifest }} exists
  stat:
    path: "{{ armada_manifest }}"
  register: stat_result

- name: check if {{ armada_manifest }} is ready
  shell: grep 'TACO_ADMIN_KEYRING' {{ armada_manifest }}
  register: grep_result
  when: stat_result.stat.exists == True
  ignore_errors: yes

- name: fetch admin_keyring from extra_vars
  shell: >-
    grep ceph_admin_keyring {{ inventory_dir }}/extra_vars.yml | awk '{print $2}'
  register: ceph_admin_keyring_str
  when: stat_result.stat.exists == False or grep_result.stdout != ""

- name: fetch mon_host from extra_vars
  shell: >-
    grep ceph_mon_host {{ inventory_dir }}/extra_vars.yml | awk '{print $2}'
  register: ceph_mon_host_str
  when: stat_result.stat.exists == False or grep_result.stdout != ""

- name: replace TACO keywords to actual values
  shell: |
    cp {{ armada_manifest_path }} {{ armada_manifest }}
    sed -i "s/TACO_ADMIN_KEYRING/{{ ceph_admin_keyring_str.stdout }}/g" {{ armada_manifest }}
    sed -i "s/TACO_MON_HOST/{{ ceph_mon_host_str.stdout }}/g" {{ armada_manifest }}
  when: stat_result.stat.exists == False or grep_result.stdout != ""

- name: check if {{ armada_manifest }} is ready
  shell: grep 'TACO_ADMIN_KEYRING' {{ armada_manifest }}
  register: grep_result
  ignore_errors: yes

- name: fail if {{ armada_manifest }} is not ready
  fail:
    msg: "Error! {{ armada_manifest }} is not ready yet!"
  when: grep_result.stdout != ""
