---
- name: check if {{ armada_manifest }} is ready
  shell: grep 'TACO_ADMIN_KEYRING' {{ armada_manifest }}
  register: grep_result
  when: taco_storage == 'ceph'
  ignore_errors: yes

- name: check if extra-vars exists
  stat:
    path: "{{ inventory_dir }}/extra-vars.yml"
  register: stat_ev_result
  when: taco_storage == 'ceph'

- name: fail if extra-vars doesn't exist
  fail:
    msg: "Error! Extra_vars doesn't exist."
  when: grep_result.stdout != "" and taco_storage == 'ceph' and stat_ev_result.stat.exists == False

- name: replace TACO keywords to actual values
  shell: |
    sed -i "s TACO_ADMIN_KEYRING {{ admin_keyring }} " {{ armada_manifest }}
    sed -i "s TACO_MON_HOST {{ mon_host }} " {{ armada_manifest }}
  when: grep_result.stdout != "" and taco_storage == 'ceph'

- name: check if {{ armada_manifest }} is ready
  shell: grep 'TACO_ADMIN_KEYRING' {{ armada_manifest }}
  register: grep_result
  ignore_errors: yes
  when: taco_storage == 'ceph'

- name: fail if {{ armada_manifest }} is not ready
  fail:
    msg: "Error! {{ armada_manifest }} is not ready yet!"
  when: grep_result.stdout != "" and taco_storage == 'ceph'
