---
- name: ensures /tmp/manifests dir exists
  file: path=/tmp/manifests state=directory

- name: copy tiller deploy yml
  template:
    src: "{{item.file}}.j2"
    dest: "/tmp/manifests/{{item.file}}"
  with_items:
    - {name: "tiller-deploy", file: tiller-deploy-nodeport.yml, type: service}
  register: manifests

- name: create nodeport for tiller
  kube:
    name: "{{item.item.name}}"
    kubectl: "{{bin_dir}}/kubectl"
    resource: "{{item.item.type}}"
    filename: "/tmp/manifests/{{item.item.file}}"
    state: "{{item.changed | ternary('latest','present') }}"
  with_items:
    - "{{ manifests.results }}"
  become: no
