---
- name: copy ceph.repo to local repository
  copy:
    src: "{{ inventory_dir }}/ceph.repo"
    dest: "{{ ceph_repository_dir }}/ceph.repo"
  when:
    - taco_storage_backend == 'ceph'
    - ceph_repository_enabled|default(false)
