---
- name: backup current repository files
  import_tasks: backup_repo_files.yml
  when:
    - local_pkg_repo_enabled or
      pkg_repo_url != ""
  ignore_errors: yes

- name: set local repo urls
  import_tasks: set_repo_urls.yml
  when:
    - local_pkg_repo_enabled or local_pip_repo_enabled or local_k8s_binary_repo_enabled or
      pkg_repo_url != ""

- name: add local centos base repo
  template:
    src: local-centosbase.repo.j2
    dest: /etc/yum.repos.d/local-centosbase.repo
  when:
    - local_pkg_repo_enabled or pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add epel repo
  template:
    src: local-epel.repo.j2
    dest: /etc/yum.repos.d/local-epel.repo
  when:
    - local_pkg_repo_enabled or pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add local ubuntu repo
  template:
    src: local-sources.list.j2
    dest: /etc/apt/sources.list
  when:
    - local_pkg_repo_enabled or pkg_repo_url != ""
    - ansible_distribution in ["Ubuntu","Debian"]

- name: add local pypi repo
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
  when: local_pip_repo_enabled or pip_repo_url != "" or pip_repo_ip != ""
