- name: set pip_repo_url
  set_fact:
    pip_repo_url: "{{ groups['package-repository'][0] }}:{{ local_reposerver_port }}"
  when: local_pip_repo_enabled

- name: set pip_repo_url
  set_fact:
    pip_repo_ip: "{{ pip_repo_url.split(':')[0] | lower }}"
  when: local_pip_repo_enabled or pip_repo_url != ""

- name: set pkg_repo_url
  set_fact:
    pkg_repo_url: "{{ groups['package-repository'][0] }}:{{ local_reposerver_port }}"
  when:
    - local_pkg_repo_enabled

- name: set package repository urls for centos
  set_fact:
    docker_rh_repo_base_url: "http://{{ pkg_repo_url }}/docker/linux/centos/7/$basearch/stable"
    docker_rh_repo_gpgkey: "http://{{ pkg_repo_url }}/docker/linux/centos/gpg"
    dockerproject_rh_repo_base_url: "http://{{ pkg_repo_url }}/dockerproject/repo/main/centos/7"
    dockerproject_rh_repo_gpgkey: "http://{{ pkg_repo_url }}/dockerproject/gpg"
  when:
    - ansible_distribution in ["CentOS", "RedHat"]
    - local_pkg_repo_enabled or pkg_repo_url != ""

- name: set pkg_repo_url for ubuntu
  set_fact:
    docker_ubuntu_repo_base_url: "http://{{ pkg_repo_url }}/docker/linux/ubuntu"
    docker_ubuntu_repo_gpgkey: "http://{{ pkg_repo_url }}/docker/linux/ubuntu/gpg"
  when:
    - ansible_distribution in ["Ubuntu", "Debian"]
    - local_pkg_repo_enabled or pkg_repo_url != ""

- name: set k8s_binary_repo_url
  set_fact:
    k8s_binary_repo_url: "{{ groups['package-repository'][0] }}:{{ local_reposerver_port }}"
  when: local_k8s_binary_repo_enabled
