- name: set pip_repo_url
  set_fact:
    pip_repo_url: "{{ groups['package-repository'][0] }}:{{ local_repo_port }}"
    pip_repo_ip: "{{ hostvars[groups['package-repository'][0]]['ansible_default_ipv4']['address'] }}"
  when: local_pip_repo_enabled

- name: set yum_repo_url
  set_fact:
    yum_repo_url: "{{ groups['package-repository'][0] }}:{{ local_repo_port }}"
    docker_rh_repo_base_url: "http://{{ yum_repo_url }}/docker/linux/centos/7/$basearch/stable"
    docker_rh_repo_gpgkey: "http://{{ yum_repo_url }}/docker/linux/centos/gpg"
    dockerproject_rh_repo_base_url: "http://{{ yum_repo_url }}/dockerproject/repo/main/centos/7"
    dockerproject_rh_repo_gpgkey: "http://{{ yum_repo_url }}/dockerproject/gpg"
  when:
    - ansible_distribution in ["CentOS", "RedHat"]
    - local_yum_repo_enabled 

- name: set apt_repo_url
  set_fact:
    apt_repo_url: "{{ groups['package-repository'][0] }}:{{ local_repo_port }}"
    docker_ubuntu_repo_base_url: "http://{{ yum_repo_url }}/docker/linux/ubuntu"
    docker_ubuntu_repo_gpgkey: "http://{{ yum_repo_url }}/docker/linux/ubuntu/gpg"
  when:
    - ansible_distribution in ["Ubuntu", "Debian"]
    - local_apt_repo_enabled

- name: set k8s_binary_repo_url
  set_fact:
    k8s_binary_repo_url: "{{ groups['package-repository'][0] }}:{{ local_repo_port }}"
  when: local_k8s_binary_repo_enabled
