---
- name: check if {{ cluster_name }} already exists
  command: grep -Frn "cluster{{ ":" }} {{ cluster_name }}" {{ lookup('env','HOME') }}/.kube/config
  register: stat_cc_result
  become: no
  when: not allow_redeployment

- name: fail if {{ cluster_name }} already exists
  fail:
    msg: "Error! {{ cluster_name }} already exists."
  when:
    - not allow_redeployment
    - stat_cc_result.rc == 0
