- hosts: localhost:all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: include global override files
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/global_taco.yml"
        - "{{ playbook_dir }}/defaults/global_k8s-cluster.yml"

    - name: include global override values - ceph
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/global_ceph.yml"
      when: taco_storage_backend == 'ceph'

    - name: include global override values - k8s images
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/global_k8s-images.yml"
      when: container_registry_enabled or (container_registries and container_registries[0].default)
    
    - name: include global override values - k8s downloads
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/global_k8s-download.yml"
      when: k8s_binary_repo_url != ""

    - name: include global override values - taco apps
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/global_taco-apps.yml"
      when: taco_apps is defined and (taco_apps|length>0)

    - name: fill TACOFIXME for validating site specific vars
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/TACOFIXME.yml"
      when: var_assert_enabled|default(false)

  tags: always
