- hosts: localhost:all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: include global override files
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/global_taco.yml"
        - "{{ playbook_dir }}/defaults/global_docker.yml"
        - "{{ playbook_dir }}/defaults/global_ceph.yml"
        - "{{ playbook_dir }}/defaults/global_k8s-cluster.yml"
        - "{{ playbook_dir }}/defaults/site_specific.yml"

    - name: include global override files
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/defaults/global_k8s-images.yml"
      when: container_registry_enabled|default(false)

    - name: check whether local repository install is needed
      set_fact:
        local_reposerver_enabled: local_pip_repo_enabled or
                                  local_pkg_repo_enabled or 
                                  local_k8s_binary_repo_enabled or 
                                  local_ceph_repo_enabled

    - name: set ceph_repository variable
      set_fact:
        ceph_repository: "{{ 'custom' if local_pkg_repo_enabled|default(false) else 'community' }}"
  tags: always
