---
- name: include global default variables
  import_playbook: include_defaults.yml

- hosts: all
  roles:
    - { role: kubespray/roles/kubespray-defaults, tags: reset }
    - { role: reset, tags: reset }

# Reset K8S cluster
- include: kubespray/reset.yml
  tags: k8s
