---
- name: include global default variables
  import_playbook: include_defaults.yml

- hosts: all
  roles:
    - { role: reset, tags: reset }

# Reset K8S cluster
- include: kubespray/reset.yml
  tags: k8s

# Purge Ceph cluster
- include: ceph-ansible/infrastructure-playbooks/purge-cluster.yml
  tags: ceph
  when: taco_storage_backend == 'ceph'
