---

- hosts: localhost:all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: include global override files
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/vars/global_taco.yml"
        - "{{ playbook_dir }}/vars/global_docker.yml"
        - "{{ playbook_dir }}/vars/global_ceph.yml"
        - "{{ playbook_dir }}/vars/global_k8s-cluster.yml"
        - "{{ playbook_dir }}/vars/site_specific.yml"

    - name: include global override files
      include_vars: "{{ item }}"
      loop:
        - "{{ playbook_dir }}/vars/global_k8s-images.yml"
      when: groups['registry'] is defined and (groups['registry'] | length > 0)

    - name: set ceph_repository variable
      set_fact:
        ceph_repository: "{{ 'custom' if localrepo_enabled else 'community' }}"
  tags: always

# Populate hostname to hosts file
- hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: make sure hostname is in hosts file
      replace:
        dest: /etc/hosts
        regexp: '^(127\.0\.0\.1(?!.*\b{{ inventory_hostname }}\b).*)$'
        replace: '\1 {{ inventory_hostname }}'
  tags: always

# Enable registry.cicd.stg.taco
- hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: registries | populate custom entries into hosts file
      lineinfile:
        path: /etc/hosts
        line: 192.168.54.30 registry.cicd.stg.taco registry-rel.cicd.stg.taco
        state: present
      when: cicd_registry_enabled|default(false)

    - name: registries | create directory for cert
      file:
        path: "/etc/docker/certs.d/{{ item }}.cicd.stg.taco"
        state: directory
      with_items:
        - registry 
        - registry-rel
      when: cicd_registry_enabled|default(false)

    - name: registries | create cert file
      copy:
        src: "{{ item }}-certs"
        dest: "/etc/docker/certs.d/{{ item }}.cicd.stg.taco/ca.crt"
      with_items:
        - registry 
        - registry-rel
      when: cicd_registry_enabled|default(false)
  tags: always

# Populate registry hosts into hosts file
- hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: populate taco registry into hosts file
      blockinfile:
        dest: /etc/hosts
        block: |-
          {% for item in (groups['registry']|default([]))|unique -%}{{ hostvars[item]['ip'] }} {{ item }}
          {% endfor %}
        state: present
        create: yes
        backup: yes
        marker: "# TACO registry hosts {mark}"
  tags: always

# Prepare OS for TACO
- hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: setup-os }
  tags: setup-os

# Add Ceph OSD
- import_playbook: ceph-ansible/infrastructure-playbooks/add-osd.yml
  tags: ceph
  when: taco_storage == 'ceph'

# TODO: add tests for checking status of the new ceph cluster

# Tune system for OpenStack
# We call this role before kubespray/scale so that the system could be ready
# before openstack pods up and run
- hosts: controller-node:compute-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: openstack/setup-os }
  tags: openstack

# Install K8S
- import_playbook: kubespray/scale.yml
  tags: k8s

# TODO: add tests for checking the status of the updated k8s cluster
