---

- name: include global default variables
  import_playbook: include_defaults.yml

- name: check if the same cluster already exists
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray/roles/kubespray-defaults, tags: setup-os }
    - { role: validate-cluster, tags: setup-os }

- name: setup host operating systems in taco host group
  hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: setup-os/conf-repos, tags: setup-os }
    - { role: setup-os, tags: setup-os }
    - { role: container-registry/client, tags: setup-os }

- name: setup docker on admin-node
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray/roles/kubespray-defaults, tags: setup-os }
    - { role: kubespray/roles/container-engine, tags: setup-os  }

- name: setup a local container registry for the offline environment
  hosts: container-registry
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray/roles/kubespray-defaults, tags: container-registry, when: container_registry_enabled }
    - { role: kubespray/roles/container-engine, tags: container-registry, when: container_registry_enabled }
    - { role: container-registry/server, tags: container-registry, when: container_registry_enabled }

- name: install ceph
  include: ceph-ansible/site.yml.sample
  tags: ceph
  when: taco_storage_backend == 'ceph'

- name: post install for ceph
  hosts: admin-node:kube-master
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: ceph/post-install, tags: ceph-post-install, when: taco_storage_backend == 'ceph' }

- name: install kubernetes
  include: kubespray/cluster.yml
  tags: k8s

- name: post install for kubernetes
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray/roles/kubespray-defaults, tags: k8s-post-install }
    - { role: k8s/post-install, tags: k8s-post-install }
    - { role: k8s/clients, tags: k8s-post-install }
    - { role: istio/deploy, tags: deploy-istio, when: istio_enabled }

- name: setup helm client for version2
  hosts: admin-node:kube-master
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: k8s/helmv2/install, tags: helmv2, when: use_helmv2_for_armada }
    - { role: k8s/helmv2/tiller, tags: helmv2, when: use_helmv2_for_armada }

# TODO: add tests for checking status of the new k8s cluster
- name: setup openstack-related config on operating system
  hosts: controller-node:compute-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/openstack/setup-os, tags: openstack, when: '"openstack" in taco_apps' }
    - { role: openvswitch, tags: openvswitch, when: ovs_package_installed }

- name: prepare lma installation
  hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/lma/pre-install, tags: lma, when: '"lma" in taco_apps' }

- name: install keycloack chart
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/keycloak/install, when: keycloak_enabled | default(false) }

- name: add a self-signed cert to ca-trust
  hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/keycloak/post-install, when: kube_oidc_auth | default(false) }

# Once we support various apps other than openstack, we should be able to
# deploy those apps selectively.
- name: deploy taco apps
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray/roles/kubespray-defaults, tags: deploy }
    - { role: taco-apps/openstack/pre-install, tags: openstack, when: '"openstack" in taco_apps' }
    - { role: taco-apps/deploy, tags: deploy, when: 'taco_apps and taco_apps|length > 0' }

- name: run opentackclient container and make os_clients.sh file for user
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco-apps/openstack/client, tags: openstack-client, when: '"openstack" in taco_apps' }
