---

- name: include global default variables
  import_playbook: include_defaults.yml

- name: setup host operating systems in taco host group
  hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: setup-os, tags: setup-os }

- name: setup a local container registry for the offline environment
  hosts: container-registry
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: container-registry, tags: container-registry }

- name: setup a local package repository for the offline environment
  hosts: package-repository
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: package-repository, tags: package-repository }

- name: copy ceph.repo to the package repository
  hosts: package-repository
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: ceph
      tags: ceph
      vars:
        copy_ceph_repo_file: true

- name: install ceph
  include: ceph-ansible/site.yml
  tags: ceph
  when: taco_storage_backend == 'ceph'

# TODO: add tests for checking status of the new ceph cluster

- name: reinstall requests package to avoid package version conflict
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - role: ceph
      tags: ceph
      vars:
        check_requests_package: true
  when: taco_storage_backend == 'ceph'

- name: update vars for ceph
  hosts: admin-node:kube-master
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: ceph/populate-ceph-vars, tags: always }
  when: taco_storage_backend == 'ceph'

- name: install kubernetes
  include: kubespray/cluster.yml
  tags: k8s

- name: install kubernetes ralated clients
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: k8s/client, tags: kubectl }
    - { role: k8s/helm, tags: helm }
    - { role: k8s/armada, tags: armada }

# TODO: add tests for checking status of the new k8s cluster

- name: install openstack
  hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco_apps/openstack/setup-os, tags: os-setup }
    - { role: taco_apps/openstack/pre-install, tags: os-pre-install }
    - { role: taco_apps/openstack/install, tags: os-install }

- name: install openstack client
  hosts: admin-node:controller-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: taco_apps/openstack/client, tags: os-client }
