---
- name: registries | populate taco registry into hosts file
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for item in (groups['container-registry']|default([]))|unique -%}{{ hostvars[item]['ip'] }} {{ item }} {% endfor %}
    state: present
    create: yes
    backup: yes
    marker: "# TACO registry hosts {mark}"
  when:
    - container_registry_enabled

- name: registries | populate taco registry into hosts file
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for item in container_registries -%}
        {% if item.endpoint and item.ip -%}
          {% if ':' in item.endpoint -%}
            {{ item.ip }} {{ item.endpoint.split(":")[0] }}
          {% else -%}
            {{ item.ip }} {{ item.endpoint }}
          {% endif -%}
        {% endif -%}
      {% endfor %}
    state: present
    create: yes
    backup: yes
  when:
    - container_registries

- name: registries | create directory for cert
  file:
    path: "/etc/docker/certs.d/{{ item.endpoint }}"
    state: directory
  when:
    - container_registries
    - item.certfile
  with_items:
    - "{{ container_registries }}"

- name: registries | create cert file
  copy:
    src: "{{ inventory_dir }}/{{ item.certfile }}"
    dest: "/etc/docker/certs.d/{{ item.endpoint }}/ca.crt"
    mode: '0644'
  when:
    - container_registries
    - item.certfile
  with_items:
    - "{{ container_registries }}"

- name: registries | set docker_insecure_registries var
  set_fact:
    docker_insecure_registries: "{{ docker_insecure_registries }} + [ '{{ groups['container-registry'][0] }}:5000' ]"
  when:
    - container_registry_enabled

- name: registries | set docker_insecure_registries var
  set_fact:
    docker_insecure_registries: "{{ docker_insecure_registries }} + [ '{{ item.endpoint }}' ]"
  when:
    - container_registries
    - not "{{ item.certfile }}"
  with_items:
    - "{{ container_registries }}"

- name: registries | debug docker_insecure_registries var
  debug:
    msg: "docker_insecure_registries has been set to: {{ docker_insecure_registries }}"
