bin_dir: /usr/local/bin
helm_repo_enabled: true
helm_repo_name: "taco-helm-repository"
helm_repo_port: 8879

chartmuseum_version: "v0.13.1"
chartmuseum_url: "https://get.helm.sh/chartmuseum-{{ chartmuseum_version }}-linux-amd64.tar.gz"
helm_servecm_url: "https://github.com/jdolitsky/helm-servecm"

source_chart_base_dir: "{{ lookup('env', 'HOME') }}/tacoplay/charts"
source_chart_list: ["taco-helm-charts/*", "taco_apps/*"]
