---
- name: install jq packages required to run taco-apps
  package:
    name: "{{ item }}"
    state: present
  loop:
    - jq

- include: prepare-openstack-manifest.yml

- include: render-openstack-manifest.yml
  when:
    - not prepare_manifest_only
    - taco_storage_backend == 'ceph'

- include: bootstrap-k8s-resources.yml
  when: not prepare_manifest_only
