# Variables used in multiple playbooks, both taco and kubespray for example,
# are defined here

bin_dir: /usr/local/bin

# kubeadm deployment mode
# # exceptionally and temporarilly, we need this here due to that kubespray checks this value from ansible host
kubeadm_enabled: true

cicd_registry_enabled: false
docker_registry: "{{ 'registry.cicd.stg.taco' if cicd_registry_enabled else groups['registry'][0] + ':5000' }}"

localrepo_enabled: true
localrepo_pypi: admin-stg
localrepo_yum: admin-stg
localrepo_k8s: admin-stg
