---
- name: set ceph_repo_url
  set_fact:
    ceph_repo_url : "{{ groups['package-repository'][0] }}:{{ local_reposerver_port }}"
  when: local_ceph_repo_enabled

- name: create ceph.repo in {{ pkg_repo_volume_path }}
  template:
    src: local-ceph.repo.j2
    dest: "{{ pkg_repo_volume_path }}/ceph.repo"
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - local_ceph_repo_enabled
