---
- name: check if registry is already running
  shell: "docker ps --filter status=running | grep {{ container_registry_name }}"
  register: registry_status
  when: not reinstall_registry
  ignore_errors: yes

- include: run-registry.yml
  when:
    - not reinstall_registry
    - registry_status.rc != 0
