---
bin_dir: /usr/local/bin

# the location of armada manifest template
armada_manifest_path: "{{ playbook_dir }}/manifests/output/{{ openstack_release }}/site-{{ site_name | default(inventory_dir.split('/')[-1]) }}-{{ openstack_release }}.yaml"

# the location of complete armada manifest
armada_manifest: "{{ inventory_dir }}/armada-manifest.yaml"

# default openstack release
openstack_release: queens

tiller_port: 32134

# TODO: remove the values below once all jinja2 variables are elimiated from template
docker_registry: "{{ 'registry.cicd.stg.taco' if cicd_registry_enabled else groups['registry'][0] + ':5000' }}"
source_type: local

