---
- name: copy admin kubeconfig to ansible host
  fetch:
    src: "/root/.kube/config"
    dest: "{{ artifacts_dir }}/admin.conf"
    flat: yes
    validate_checksum: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: create kube config dir
  file:
    path: "{{ lookup('env','HOME') }}/.kube"
    mode: "0700"
    state: directory
  become: no

- name: copy admin kubeconfig to home
  copy:
    src: "{{ artifacts_dir }}/admin.conf"
    dest: "{{ lookup('env','HOME') }}/.kube/config"
  become: no

- name: copy kubectl binary to ansible host
  fetch:
    src: "{{ bin_dir }}/kubectl"
    dest: "{{ artifacts_dir }}/kubectl"
    flat: yes
    validate_checksum: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: copy kubectl to bin_dir
  copy:
    src: "{{ artifacts_dir }}/kubectl"
    dest: "{{ bin_dir }}/kubectl"
    mode: 0755

- name: copy helm binary to ansible host
  fetch:
    src: "{{ bin_dir }}/helm"
    dest: "{{ artifacts_dir }}/helm"
    flat: yes
    validate_checksum: no
  become: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: copy helm to bin_dir
  copy:
    src: "{{ artifacts_dir }}/helm"
    dest: "{{ bin_dir }}/helm"
    mode: 0755
