---
- include: prepare-openstack-manifest.yml
  when: '"openstack" in taco_apps'

- include: render-openstack-manifest.yml
  when:
    - '"openstack" in taco_apps'
    - taco_storage_backend == 'ceph'

- name: set starting option and virtualenv folder in bashrc for centos
  set_fact:
    starting_option_folder: ".bashrc"
    virtualenv_folder: "/usr/bin/virtualenvwrapper.sh"
  when: ansible_distribution in ["CentOS","RedHat"] and armada_enabled|default(true)

- name: set starting option and virtualenv folder in profile for ubuntu
  set_fact:
    starting_option_folder: ".profile"
    virtualenv_folder: "/usr/local/bin/virtualenvwrapper.sh"
  when: ansible_distribution in ["Ubuntu","Debian"] and armada_enabled|default(true)

- name: delete test pods in openstack namespace
  shell: >-
    {{ bin_dir }}/kubectl get pods -n openstack | grep test |
    awk '{print $1}' | xargs {{ bin_dir }}/kubectl delete pods -n openstack
  ignore_errors: yes
  when: '"openstack" in taco_apps'

- name: check host where tiller is running
  shell: >-
    {{ bin_dir }}/kubectl get pods -n kube-system -o json |
    jq -r '.items[] | select(.metadata.name|test("tiller")).status.hostIP'
  register: tiller_host
  become: no

- name: delete armada lock
  shell: >-
    {{ bin_dir }}/kubectl delete lock --all -n kube-system
  become: no
  ignore_errors: yes

- name: get existing armada processes
  shell: >-
    ps -ef | grep -v grep | grep -w 'armada apply' | awk '{print $2}'
  register: armada_processes
  become: no

- name: kill existing armada processes
  shell: kill {{ item }}
  with_items: "{{ armada_processes.stdout_lines }}"
  become: no

- name: wait until existing armada processes are killed
  wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ armada_processes.stdout_lines }}"

- name: run armada apply 
  shell: >-
    . {{ lookup('env','HOME') }}/{{ starting_option_folder }} && workon armada &&
    ~/venv/armada/bin/armada apply
    --tiller-host {{ tiller_host.stdout }}
    --tiller-port {{ tiller_port }}
    --timeout 7200
    {{ inventory_dir }}/{{ item }}-manifest.yml >
    {{ lookup('env','HOME') }}/{{ item }}-deployment.log
  when: auto_release_enabled|default(true) and tiller_host.stdout != ""
  become: no
  args:
    executable: /bin/bash
  run_once: yes
  with_items: taco_apps

- name: show armada apply usage for next try
  debug:
    msg: >-
      ". ~/.bashrc &&
      workon armada &&
      armada apply
      --tiller-host {{ tiller_host.stdout }}
      --tiller-port {{ tiller_port }}
      --timeout 7200
      {{ inventory_dir }}/[YOUR_APP]-manifest.yaml"
  when: tiller_host.stdout != ""
