---
- name: delete manifest configmap
  shell: >-
    {{ bin_dir }}/kubectl delete configmap {{ item }}
  when: item != "istio"
  with_items:
    - "{{ taco_apps }}"
  become: false
  ignore_errors: true

- name: create manifest configmap
  shell: >-
    {{ bin_dir }}/kubectl create configmap {{ item }} --from-file={{ inventory_dir }}/decapod/{{ item }}-manifest.yaml
  when: item != "istio"
  with_items:
    - "{{ taco_apps }}"
  become: false

- name: deploy apps
  shell: >-
    {{ bin_dir }}/argo submit {{ inventory_dir }}/decapod/{{ item }}-wf.yaml
  when: item != "istio"
  with_items:
    - "{{ taco_apps }}"
  become: false
