ceph_stable_release: luminous
ceph_origin: repository
ceph_repository: community
ceph_mirror: http://hk.ceph.com

ntp_service_enabled: false
copy_admin_key: false
external_cluster_mon_ips: 192.168.48.31
