ceph_stable_release: luminous
ceph_origin: repository
ceph_repository: custom
ceph_custom_repo: "http://admin-stg/ceph/ceph.repo"

ntp_service_enabled: false
copy_admin_key: false
external_cluster_mon_ips: 192.168.51.20
