ceph_stable_release: luminous
ceph_origin: repository
ceph_repository: >-
  {%- if localrepo_enabled -%}custom{%- else -%}community{%- endif -%}
ceph_custom_repo: "http://{{ localrepo_yum }}/ceph/ceph.repo"
ceph_mirror: http://hk.ceph.com

ntp_service_enabled: false
copy_admin_key: true
ceph_mgr_modules: [status,dashboard,prometheus]

monitor_interface: bond0
public_network: 192.168.51.0/24
cluster_network: 192.168.51.0/24

osd_objectstore: bluestore
osd_scenario: lvm

ceph_conf_overrides:
  global:
    mon_allow_pool_delete: true
    osd_pool_default_size: 3
    osd_pool_default_min_size: 2
    osd_pg_stat_report_internal_max: 1

crush_rule_config: true

crush_rule_hdd:
  name: hdd-donotuse
  root: default
  type: host
  default: false

crush_rule_ssd:
  name: ssd-donotuse
  root: default
  type: host
  default: false

crush_rules:
  - "{{ crush_rule_hdd }}"
  - "{{ crush_rule_ssd }}"

create_crush_tree: true

openstack_config: true
# PG Calc: Total 21 OSDs ( 17 SSD + 4 HDD ): all 3 copies
#  kube -> 20%, SSD
#  glance -> 20%, SSD
#  cinder-ssd -> 55%, SSD
#  cinder-backup -> 5%, SSD
#  lma -> 20%, HDD
#  cinder-hhd -> 80%, HD
kube_pool:
  name: "kube"
  pg_num: 128
  pgp_num: 128
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
lma_pool:
  name: "lma"
  pg_num: 32
  pgp_num: 32
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
  application: "rbd"
openstack_glance_pool:
  name: "images"
  pg_num: 128
  pgp_num: 128
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
openstack_cinder_ssd_pool:
  name: "volumes-ssd"
  pg_num: 256
  pgp_num: 256
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
openstack_cinder_hdd_pool:
  name: "volumes-hdd"
  pg_num: 128
  pgp_num: 128
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""
openstack_cinder_backup_pool:
  name: "backups"
  pg_num: 32
  pgp_num: 32
  rule_name: "replicated_rule"
  type: 1
  erasure_profile: ""
  expected_num_objects: ""

openstack_pools:
  - "{{ kube_pool }}"
  - "{{ lma_pool }}"
  - "{{ openstack_glance_pool }}"
  - "{{ openstack_cinder_ssd_pool }}"
  - "{{ openstack_cinder_hdd_pool }}"
  - "{{ openstack_cinder_backup_pool }}"

openstack_keys:
  - { name: client.kube, caps: { mon: "profile rbd", osd: "profile rbd pool=kube, profile rbd pool=lma"}, key: "AQAPn8tUmPBwCxAAeIfvpDKA1fGvrBeXGdc6xQ==", mode: "0600" }
  - { name: client.cinder, caps: { mon: "profile rbd", osd: "profile rbd pool=volumes-ssd, profile rbd pool=volumes-hdd, profile rbd pool=backups, profile rbd pool=images"}, key: "AQAin8tU0CFgEhAATb7sYgtWsh+S5HEbg6MrGg==",  mode: "0600" }
