ceph_stable_release: luminous
ceph_origin: repository
ceph_repository: community
ceph_mirror: http://hk.ceph.com
#ceph_repository: custom
#ceph_custom_repo: "http://{{ localrepo_yum }}/ceph/ceph.repo"

ntp_service_enabled: false
copy_admin_key: false
external_cluster_mon_ips: 192.168.51.20
