---

- import_tasks: setup-interfaces.yml

- name: disable default centos base and epel repo
  args:
    chdir: /etc/yum.repos.d
  shell: mv {{ item }} {{ item }}.bak
  with_items:
    - CentOS-Base.repo
    - CentOS-CR.repo
    - CentOS-Debuginfo.repo
    - CentOS-Media.repo
    - CentOS-Sources.repo
    - CentOS-Vault.repo
    - CentOS-fasttrack.repo
    - epel.repo
    - epel-testing.repo
    - ceph_stable.repo
    - docker.repo
  when:
    - localrepo_enabled
    - replace_repo_file
    - ansible_distribution in ["CentOS","RedHat"]
  ignore_errors: yes

- name: add local centos base repo
  template:
    src: localrepo.repo.j2
    dest: /etc/yum.repos.d/localrepo.repo
  when:
    - localrepo_enabled
    - replace_repo_file
    - ansible_distribution in ["CentOS","RedHat"]

- name: add epel repo
  template:
    src: epel.repo.j2
    dest: /etc/yum.repos.d/epel.repo
  when:
    - localrepo_enabled
    - replace_repo_file
    - ansible_distribution in ["CentOS","RedHat"]

- name: add local pypi repo
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
  when: localrepo_enabled and replace_repo_file

- name: add ceph apt-key
  apt_key:
    url: http://tacorepo:8888/ceph/keys/release.asc
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]

- import_tasks: setup-net-services.yml

# Install ovs by rpms for sona
- import_tasks: openvswitch.yml
  when: 
    - inventory_hostname in groups['compute-node']
    - install_ovs_as_a_rpms
