---

- name: make sure hostname is in hosts file
  replace:
    dest: /etc/hosts
    regexp: '^(127\.0\.0\.1(?!.*\b{{ inventory_hostname }}\b).*)$'
    replace: '\1 {{ inventory_hostname }}'

- name: change sh directory from dash to bash
  shell: >-
    rm /bin/sh &&
    ln -s /bin/bash /bin/sh
  when:
    - ansible_distribution in ["Ubuntu","Debian"]

- import_tasks: setup-interfaces.yml

- import_tasks: setup-net-services.yml

# Install ovs by rpms for sona
- import_tasks: openvswitch.yml
  when: 
    - inventory_hostname in groups['compute-node']
    - install_ovs_as_a_rpms
