---

- name: disable zeroconf for CentOS
  lineinfile:
    path: "/etc/sysconfig/network"
    line: "NOZEROCONF=yes"
    create: yes
    state: present
  when: ansible_distribution in ["CentOS","RedHat"]

- name: TC | install TC script
  template:
    src: tc-service.j2
    dest: "{{ bin_dir }}/tc-service"
    mode: 755
  when: tc_enabled

- name: TC | create TC service
  template:
    src: tc.service.j2
    dest: /etc/systemd/system/tc.service
    mode: 644
  when: tc_enabled

- name: TC | start TC service
  service:
    name: tc.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: tc_enabled

- name: NAT | install NAT script
  template:
    src: nat-service.j2
    dest: "{{ bin_dir }}/nat-service"
    mode: 755
  when: nat_enabled

- name: NAT | create NAT service
  template:
    src: nat.service.j2
    dest: /etc/systemd/system/nat.service
    mode: 644
  when: nat_enabled

- name: NAT | start NAT service
  service:
    name: nat.service
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: nat_enabled

- name: check firewalld installation on redhat
  command: rpm -q firewalld
  args:
    warn: no
  register: firewalld_pkg_query
  ignore_errors: true
  check_mode: no
  changed_when: false
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: make sure firewalld stoppend and disabled
  service:
    name: firewalld
    state: stopped
    enabled: no
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - firewalld_pkg_query.rc == 0

- name: disable default centos base and epel repo
  args:
    chdir: /etc/yum.repos.d
  shell: mv {{ item }} {{ item }}.bak
  with_items:
    - CentOS-Base.repo
    - CentOS-CR.repo
    - CentOS-Debuginfo.repo
    - CentOS-Media.repo
    - CentOS-Sources.repo
    - CentOS-Vault.repo
    - CentOS-fasttrack.repo
    - epel.repo
    - epel-testing.repo
    - ceph_stable.repo
    - docker.repo
  when:
    - localrepo_enabled
    - replace_repo_file
    - ansible_distribution in ["CentOS","RedHat"]
  ignore_errors: yes

- name: add local centos base repo
  template:
    src: localrepo.repo.j2
    dest: /etc/yum.repos.d/localrepo.repo
  when:
    - localrepo_enabled
    - replace_repo_file
    - ansible_distribution in ["CentOS","RedHat"]

- name: add epel repo
  template:
    src: epel.repo.j2
    dest: /etc/yum.repos.d/epel.repo
  when:
    - localrepo_enabled
    - replace_repo_file
    - ansible_distribution in ["CentOS","RedHat"]

- name: add local pypi repo
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
  when: localrepo_enabled and replace_repo_file
