override_system_hostname: false

# Etcd
etcd_deployment_type: docker

# K8S
kube_version: v1.12.3
pod_infra_version: 3.1

kubeadm_enabled: true
kube_network_plugin: calico
kube_proxy_mode: iptables
kubelet_deployment_type: host

rbd_provisioner_enabled: true
local_volume_provisioner_enabled: false
cephfs_provisioner_enabled: false

# Dashboard
dashboard_enabled: true

# DNS
dns_mode: coredns

# Helm
helm_enabled: true
helm_deployment_type: host
helm_version: "v2.11.0"
