# default options
openstack_namespace: openstack

# mon_host and admin_keyring would be set automatically
# from /etc/ceph/ceph.conf and ceph.client.admin.keyring
# once ceph is installed by ceph-ansible
# set the values only when using exsiting ceph
ceph_enabled: true
mon_host: ''
admin_keyring: ''

# additional host configurations
config_drive_enabled: true
tc_enabled: false
nat_enabled: true
nat_interfaces:
  - bond1

armada_venv: "{{ lookup('env','HOME') }}/venv"

db_root_user: "pcl_admin"
db_root_password: "Pcl.6831!"
db_keystone_password: "Pcl.6831!"
db_nova_password: "vlzmf21!"
db_cinder_password: "vlzmf21!"
db_glance_password: "vlzmf21!"
db_neutron_password: "vlzmf21!"
db_heat_password: "vlzmf21!"
db_horizon_password: "vlzmf21!"
db_grafana_password: "vlzmf21!"
db_grafana_session_password: "vlzmf21!"
