---
- name: Reset OpenvSwitch
  include_tasks: reset-openvswitch.ym
  when:
    - ovs_package_installed
    - inventory_hostname in groups['controller-node'] or inventory_hostname in groups['compute-node']

- name: remove SONA configuration
  include_tasks: reset-sona-configuration.ym
  when: sona_integration|default(false)

- name: Restore OpenStack manifest to previous state
  shell: |
    sed -i "s/admin_keyring:.*/admin_keyring: TACO_ADMIN_KEYRING/" {{ openstack_manifest }}
    sed -i "s/mon_host:.*/mon_host: TACO_MON_HOST/" {{ openstack_manifest }}
  when:
    - taco_storage_backend == 'ceph'
    - inventory_hostname in groups['admin-node']
  ignore_errors: yes

- name: delete helm2 binary file
  file:
    path: "{{ bin_dir }}/helm2"
    state: absent
  when:
    - inventory_hostname in groups['admin-node']
    - use_helmv2_for_armada

- name: delete all configurations for helm2
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ lookup('env','HOME') }}/.helm"
  become: no
  when:
    - inventory_hostname in groups['admin-node']
    - use_helmv2_for_armada

- name: Remove {{ cluster_name }} config
  file:
    path: "$HOME/.kube/{{ cluster_name }}-config"
    state: absent

- name: Remove {{ cluster_name }} from bashrc
  replace:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    regexp: '\$HOME\/.kube\/{{ cluster_name }}-config:|:\$HOME\/.kube\/{{ cluster_name }}-config|^(export KUBECONFIG=\$HOME\/.kube\/cluster.local-config)$'

- name: source bashrc
  become: no
  shell: source {{ lookup('env','HOME') }}/.bashrc
  args:
    executable: /bin/bash
