---
- name: Reset OpenvSwitch
  include_tasks: reset-openvswitch.yml
  when:
    - ovs_package_installed
    - inventory_hostname in groups['controller-node'] or inventory_hostname in groups['compute-node']

- name: remove SONA configuration
  include_tasks: reset-sona-configuration.yml
  when: sona_integration|default(false)

- name: Restore OpenStack manifest to previous state
  shell: |
    sed -i "s/admin_keyring:.*/admin_keyring: TACO_ADMIN_KEYRING/" {{ openstack_manifest }}
    sed -i "s/mon_host:.*/mon_host: TACO_MON_HOST/" {{ openstack_manifest }}
  when:
    - taco_storage_backend == 'ceph'
    - inventory_hostname in groups['admin-node']
  ignore_errors: yes

- name: Remove {{ cluster_name }} context from .kube/config
  become: no
  shell: >-
    {{ bin_dir }}/kubectl config delete-context kubernetes-admin-{{ cluster_name }}@{{ cluster_name }}
  ignore_errors: yes 
  when:
    - inventory_hostname in groups['admin-node']

- name: Remove {{ cluster_name }} cluster from .kube/config
  become: no
  shell: >-
    {{ bin_dir }}/kubectl config delete-cluster {{ cluster_name }}
  ignore_errors: yes 
  when:
    - inventory_hostname in groups['admin-node']

- name: Remove {{ cluster_name }} cluster's user from .kube/config
  become: no
  shell: >-
    {{ bin_dir }}/kubectl config unset users.kubernetes-admin-{{ cluster_name }}
  ignore_errors: yes 
  when:
    - inventory_hostname in groups['admin-node']
