# For gating job
is_gating_test: false

# Set this to 'true' to exclude k8s component images in site-prepare job
exclude_k8s_images: false

rbd_provisioner_image_repo: "docker.io/sktdev/rbd-provisioner"
rbd_provisioner_image_tag: "v2.1.1-nautilus-14.2.4"
openstackclient_image_repo: "docker.io/sktdev/openstackclient"
openstackclient_image_tag: "stein"

# These values are defined in global_taco vars since these are
# shared by container-registry and prepare-artifact role.
# container_registry_image_repo: "registry"
# container_registry_image_tag: "2.6.2"

# Since prepare-artifact role is called from extra-playbook directory,
# the volume_dir should be set to upper directory of the playbook_dir
container_registry_volume_relative_dir: "{{ playbook_dir | dirname }}/container_registry"

decapod_site_yaml_source: "https://github.com/openinfradev/decapod-site-yaml"
decapod_site_yaml_dest: "/tmp/decapod_site_yaml"
decapod_site_yaml_version: "test-download-helm-chart"
