# For gating job
is_gating_test: false

# Set this to 'true' to exclude k8s component images in site-prepare job
exclude_k8s_images: false

openstackclient_image_repo: "docker.io/sktdev/openstackclient"
openstackclient_image_tag: "stein"

# These values are defined in global_taco vars since these are
# shared by container-registry and prepare-artifact role.
# container_registry_image_repo: "registry"
# container_registry_image_tag: "2.6.2"

# Since prepare-artifact role is called from extra-playbook directory,
# the volume_dir should be set to upper directory of the playbook_dir
container_registry_volume_relative_dir: "{{ playbook_dir | dirname }}/container_registry"

decapod_site_source: "https://github.com/openinfradev/decapod-site"
decapod_site_dest: "/tmp/decapod_site"
decapod_site_version: "main"
decapod_base_yaml_version: "main"
decapod_preperation_site_name: "hanu-reference"

# The following images were added because they cannot be processed
# by tacoplay/scripts/download_container_images.py
download_container_images:
  - { repo: quay.io/prometheus-operator/prometheus-config-reloader, tag: v0.48.0}
