---
- name: copy ceph.repo to local repository
  copy:
    src: "{{ inventory_dir }}/ceph.repo"
    dest: "{{ ceph_repository_dir }}/ceph.repo"
  when:
    - taco_storage == 'ceph'
    - ceph_repository_enabled|default(false)
    - copy_ceph_repo_file

- name: rpm check requests
  shell: rpm -qa | grep requests
  register: check_result
  ignore_errors: true
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - check_requests_package

- name: reinstall python-requests if requests installed with dist package
  pip:
    name: requests
    extra_args: --ignore-installed
  when:
    - ansible_distribution in ["CentOS","RedHat"]
    - check_result.rc == 0
    - check_requests_package
