---

- name: install packages required for openstack client packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - python-devel
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: install python-openstackclient
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  loop:
    - { name: 'pbr', version: '5.1.1' }
    - { name: 'python-openstackclient', version: '3.16.0' }
    - { name: 'python-cinderclient', version: '3.1.0' }
    - { name: 'python-glanceclient', version: '2.8.0' }
    - { name: 'python-keystoneclient', version: '3.17.0' }
    - { name: 'python-novaclient', version: '9.1.2' }

- name: update bashrc for openstack client configs
  blockinfile:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    block: |
      export OS_AUTH_URL={{ os_auth_url }}
      export OS_IDENTITY_API_VERSION=3
      export OS_IMAGE_API_VERSION=2
      export OS_PROJECT_DOMAIN_NAME={{ os_project_domain }}
      export OS_USER_DOMAIN_NAME={{ os_user_domain }}
      export OS_PROJECT_NAME={{ os_project_name }}
      export OS_USERNAME={{ os_user_name }}
      export OS_PASSWORD={{ os_password }}
    marker: "# OPENSTACK CLIENT ENVS {mark}"
  become: no

- name: check host where ingress controller is running
  shell: >-
    {{ bin_dir }}/kubectl get po -n openstack -o wide |
    grep "^ingress-[^error]" |
    awk '{print $6}'
  retries: 10
  delay: 10
  register: ingress_host
  until: ingress_host.stdout != ""
  become: no
  delegate_to: "{{ groups['admin-node']|first }}"
  when: auto_release_enabled|default(true)

- fail:
    msg: "ingress controller is not running"
  when: auto_release_enabled|default(true) and ingress_host.stdout == ""

- name: get ingress configmap
  shell: >-
    {{ bin_dir }}/kubectl get cm ingress-conf -n openstack -o json
  retries: 10
  delay: 5
  register: configmap_raw
  become: no
  delegate_to: "{{ groups['admin-node']|first }}"
  until: configmap_raw.rc == 0

- name: extract configmap result
  set_fact:
    result: "{{ configmap_raw.stdout | from_json }}"

- name: set fact of bind-address
  set_fact:
    bind_address: "{{ result['data']['bind-address'] }}"

- name: update hosts file for openstack services with ingress node ip
  blockinfile:
    path: /etc/hosts
    block: |
      {{ ingress_host.stdout }} keystone.openstack.svc.cluster.local
      {{ ingress_host.stdout }} glance.openstack.svc.cluster.local
      {{ ingress_host.stdout }} nova.openstack.svc.cluster.local
      {{ ingress_host.stdout }} neutron.openstack.svc.cluster.local
      {{ ingress_host.stdout }} cinder.openstack.svc.cluster.local
    state: present
    marker: "# OPENSTACK SERVICES {mark}"
  when: auto_release_enabled|default(true) and bind_address == ""

- name: update hosts file for openstack services with ingress vip
  blockinfile:
    path: /etc/hosts
    block: |
      {{ bind_address }} keystone.openstack.svc.cluster.local
      {{ bind_address }} glance.openstack.svc.cluster.local
      {{ bind_address }} nova.openstack.svc.cluster.local
      {{ bind_address }} neutron.openstack.svc.cluster.local
      {{ bind_address }} cinder.openstack.svc.cluster.local
    state: present
    marker: "# OPENSTACK SERVICES {mark}"
  when: auto_release_enabled|default(true) and bind_address != ""
