---

- name: install packages required for openstack client packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - python-devel
    - epel-release
    - python-pip
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: install python-openstackclient
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    state: present
  loop:
    - { name: 'pbr', version: '5.1.1' }
    - { name: 'python-openstackclient', version: '4.0.0' }
    - { name: 'python-cinderclient', version: '3.1.0' }
    - { name: 'python-glanceclient', version: '2.8.1' }
    - { name: 'python-keystoneclient', version: '3.12.0' }
    - { name: 'python-novaclient', version: '9.1.1' }
    - { name: 'python-neutronclient', version: '6.5.1' }

- name: update bashrc for openstack client configs
  blockinfile:
    path: "{{ lookup('env','HOME') }}/.bashrc"
    block: |
      export OS_AUTH_URL={{ os_auth_url }}
      export OS_IDENTITY_API_VERSION=3
      export OS_IMAGE_API_VERSION=2
      export OS_PROJECT_DOMAIN_NAME={{ os_project_domain }}
      export OS_USER_DOMAIN_NAME={{ os_user_domain }}
      export OS_PROJECT_NAME={{ os_project_name }}
      export OS_USERNAME={{ os_user_name }}
      export OS_PASSWORD={{ os_password }}
    marker: "# OPENSTACK CLIENT ENVS {mark}"
  become: no

- name: check host where ingress controller is running
  shell: >-
    {{ bin_dir }}/kubectl describe ep ingress -n openstack |
    grep Addresses |
    grep -v NotReady |
    awk '{split($2,a,",");print a[1]"\n"a[2]"\n"a[3]}' |
    awk NF
  retries: 20
  delay: 10
  register: ingress_host
  until: ingress_host.stdout != ""
  become: no
  delegate_to: "{{ groups['admin-node']|first }}"
  when: auto_release_enabled|default(true)

- fail:
    msg: "ingress controller is not running"
  when: auto_release_enabled|default(true) and ingress_host.stdout == ""

- name: update hosts file for openstack services with ingress node ip
  blockinfile:
    path: /etc/hosts
    block: |
      {{ ingress_host.stdout }} keystone.openstack.svc.cluster.local
      {{ ingress_host.stdout }} glance.openstack.svc.cluster.local
      {{ ingress_host.stdout }} nova.openstack.svc.cluster.local
      {{ ingress_host.stdout }} neutron.openstack.svc.cluster.local
      {{ ingress_host.stdout }} cinder.openstack.svc.cluster.local
    state: present
    marker: "# OPENSTACK SERVICES {mark}"
  when: auto_release_enabled|default(true)
