---
# import global vars
- name: include global default variables
  import_playbook: include_defaults.yml

# setup local repositories
- name: setup a local package repository for the offline environment
  hosts: package-repository
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: package-repository/install, tags: package-repository, when: local_reposerver_enabled }

- name: configure package repositories
  hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: package-repository/conf-repos, tags: package-repository }

- name: setup host operating systems in taco host group
  hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: setup-os, tags: setup-os }
    - { role: container-registry/client, tags: setup-os }

# Use current docker role for now. Kubespray's container-engine role
# can be considered later.
- name: setup a local container registry for the offline environment
  hosts: container-registry
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: docker, tags: container-registry, when: container_registry_enabled }
    - { role: container-registry/server, tags: container-registry, when: container_registry_enabled }

# Install ironic standalone
- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  become: yes
  roles:
    - { role: ironic, tags: ironic }
