---
# import global vars
- name: include global default variables
  import_playbook: ../include_defaults.yml

- name: setup host operating systems in taco host group
  hosts: taco
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: setup-os, tags: setup-os }
    - { role: container-registry/client, tags: setup-os }

- name: setup a local container registry for the offline environment
  hosts: container-registry
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: ../kubespray/roles/kubespray-defaults, tags: container-registry, when: container_registry_enabled }
    - { role: ../kubespray/roles/container-engine, tags: container-registry, when: container_registry_enabled }
    - { role: container-registry/server, tags: container-registry, when: container_registry_enabled }

# Install ironic standalone
- hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  become: yes
  roles:
    - { role: ironic, tags: ironic }
