- hosts: admin-node
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: run reset.yml without confirmation
      command:
        chdir: "{{ playbook_dir }}/.."
        cmd: ansible-playbook -vv -u taco -b -i {{ inventory_dir }}/hosts.ini reset.yml -e @{{ inventory_dir }}/extra-vars.yml -e reset_confirmation=yes -e ireallymeanit=yes
