---
- hosts: localhost:all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  tasks:
    - name: include global override files
      include_vars: "{{ item }}"
      loop:
        - "../defaults/global_taco.yml"
        - "../defaults/global_docker.yml"
        - "../defaults/global_ceph.yml"
        - "../defaults/global_k8s-cluster.yml"
        - "../defaults/global_k8s-images.yml"
  tags: always

- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: docker }
    - { role: container-registry/client }
    - { role: extra-roles/install-yaml-tools }
  tags: always

- import_playbook: ../kubespray/cluster.yml
  when: not exclude_k8s_images

- hosts: localhost
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: extra-roles/prepare-artifact }
  tags: always
