---
- name: Copy cert to dest servers
  copy:
    src: /etc/keycloak/ssl/keycloak.crt
    dest: /etc/pki/ca-trust/source/anchors/
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: update trust ca
  shell: |
    sudo update-ca-trust
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: Copy cert to dest servers
  copy:
    src: /etc/keycloak/ssl/keycloak.crt
    dest: /usr/local/share/ca-certificates/
  when:
    - ansible_distribution in ["Ubuntu","Debian"]

- name: update trust ca
  shell: |
    sudo update-ca-certificates
  when:
    - ansible_distribution in ["Ubuntu","Debian"]


