---
- name: populate the taco repo into hosts file
  blockinfile:
    dest: /etc/hosts
    block: |-
      {% for item in (groups['package-repository']|default([]))|unique -%}{{ hostvars[item]['ip'] }} {{ item }}
      {% endfor %}
    state: present
    create: yes
    backup: yes
    marker: "# TACO local repo host {mark}"

- name: ensure local package repository exist
  file:
    state: directory
    path: "{{ item | regex_replace('^(?P<host>.+):(?P<container>.+):(?P<mode>.+)', '\\g<host>') }}"
  with_items:
    - "{{ pkg_repo_volume_path }}"

- name: extract package repository archive to {{ pkg_repo_volume_path }}
  unarchive:
    src: "{{ pkg_repo_volume_archive_file }}"
    dest: "{{ pkg_repo_volume_path }}"
  when: pkg_repo_volume_archived

- name: kill existing web server
  raw: pkill busybox
  ignore_errors: true

- name: run web server for temporary package repositories
  raw: "{{ role_path }}/files/busybox-x86_64 httpd -p {{ local_repo_port}} -h {{ pkg_repo_volume_path}}"
  register: busybox_cmd
  failed_when: busybox_cmd.rc != 0

- name: install Apache web server
  yum:
    name: httpd
    state: present

- name: kill temporary repository web server
  raw: pkill busybox

- name: Configure Apache web server
  lineinfile:
    dest: "{{ apache_server_root }}/conf/{{ apache_daemon }}.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ apache_configuration_items }}"

- name: restart httpd
  service:
    name: httpd
    state: restarted

