---
- name: create namespace to deploy argo
  shell: >-
    {{ bin_dir }}/kubectl create namespace argo
  ignore_errors: true
  become: false

- name: install argo chart
  shell: >-
    {{ bin_dir }}/helm install argo {{ argo_chart_source }} -n argo \
    --set workflowArchive.enabled={{ argo_workflow_archive_enabled }} \
    --set mysql.enabled={{ argo_workflow_archive_enabled }} \
    --set workflowController.image.repository={{ argo_workflow_controller_image_repo }} \
    --set workflowController.image.tag={{ argo_version }} \
    --set workflowController.executor.image.repository={{ argo_workflow_executor_image_repo }} \
    --set workflowController.executor.image.tag={{ argo_version }} \
    --set argoServer.image.repository={{ argo_server_image_repo }} \
    --set argoServer.image.tag={{ argo_version }} \
    --set nodeSelector={{ argo_node_selector }} \
    --set mysql.image.repository={{ argo_mysql_image_repo }} \
    --set mysql.image.tag={{ argo_mysql_version }} \
    --set mysql.persistence.storageClass={{ taco_storageclass_name }} \
    --set mysql.persistence.size={{ argo_archive_storage_size }} \
    --set mysql.nodeSelector={{ argo_node_selector }}
  become: false

- name: wait for argo pods become ready
  shell: >-
    {{ bin_dir }}/kubectl wait --namespace=argo --for=condition=Ready pods -l app={{ item }} --timeout=600s
  become: false
  delay: 10
  retries: 3
  with_items:
    - argo-server
    - workflow-controller
  register: argo_pods_result
  until: argo_pods_result is not failed

- name: check argo client binary exists
  stat:
    path: "{{ role_path }}/files/{{ argo_client_binary_name }}.gz"
  register: stat_argo_cli_result
  tags: download

- name: download argo client binary
  shell: >-
    curl -L {{ argo_client_url }} -o {{ role_path }}/files/{{ argo_client_binary_name }}.gz
  when: not stat_argo_cli_result.stat.exists
  tags: download

- name: check argo client installed
  stat:
    path: "{{ bin_dir }}/argo"
  register: stat_argo_bin_result

- name: install argo client
  shell: >-
    gunzip {{ role_path }}/files/{{ argo_client_binary_name }}.gz -c > {{ role_path }}/files/{{ argo_client_binary_name }} && chmod +x {{ role_path }}/files/{{ argo_client_binary_name }} && cp {{ role_path }}/files/{{ argo_client_binary_name }} {{ bin_dir }}/argo
  become: true
  when: not stat_argo_bin_result.stat.exists

- name: granting admin privileges into default serviceaccount
  shell: >-
    {{ bin_dir }}/kubectl create rolebinding default-admin --clusterrole=admin --serviceaccount=argo:default -n argo
  become: false
  ignore_errors: True
