---
- import_tasks: helm-operator.yml
- import_tasks: argo.yml
- import_tasks: argocd.yml

- name: git clone decapod-flow
  git:
    repo: "{{ decapod_flow_source }}"
    dest: "{{ decapod_flow_dest }}"
    version: "{{ decapod_flow_version }}"
  become: false

- name: copy helmrelease-rbac.yaml to tmp
  copy:
    src: "{{ decapod_flow_dest }}/templates/helm-operator/helmrelease-rbac.yaml"
    dest: "/tmp/.helmrelease-rbac.yaml"
  become: false

- name: install rbac to argo for helmrelase
  shell: >-
    {{ bin_dir }}/kubectl apply -f /tmp/.helmrelease-rbac.yaml
  become: false

- name: copy argo-additional-rbac.yaml to tmp
  copy:
    src: "{{ decapod_flow_dest }}/templates/argo-additional-rbac.yaml"
    dest: "/tmp/.argo-additional-rbac.yaml"
  become: false

- name: install rbac to argo for argo:default serviceaccount
  shell: >-
    {{ bin_dir }}/kubectl apply -f /tmp/.argo-additional-rbac.yaml
  become: false

- name: check createapp-wftpl is exist
  shell: >-
    {{ bin_dir }}/argo template get create-application -nargo
  ignore_errors: true
  register: shell_result
  become: false

- name: remove create-application wftpl
  shell: >-
    {{ bin_dir }}/argo template delete create-application -nargo
  when: not shell_result.failed
  become: false

- name: summit create-application workflow template to argo
  shell: >-
    {{ bin_dir }}/argo template create {{ decapod_flow_dest }}/templates/argo-cd/createapp-wftpl.yaml -nargo
  become: false

- name: check prepare-argocd is exist
  shell: >-
    {{ bin_dir }}/argo template get prepare-argocd -nargo
  ignore_errors: true
  register: shell_result
  become: false

- name: remove prepare-argocd wftpl
  shell: >-
    {{ bin_dir }}/argo template delete prepare-argocd -nargo
  when: not shell_result.failed
  become: false

- name: summit prepare-manifest workflow template to argo
  shell: >-
    {{ bin_dir }}/argo template create {{ decapod_flow_dest }}/templates/argo-cd/prepare-argocd-wftpl.yaml -nargo
  become: false

- name: delete decapod by-products
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ decapod_flow_source }}"
    - /tmp/.helmrelease-rbac.yaml

- name: run prepare-argocd workflow
  shell: >-
    {{ bin_dir }}/argo submit --watch --from wftmpl/prepare-argocd -p argo_password={{ argocd_admin_password  }}
  become: false
