bin_dir: /usr/local/bin
decapod_enabled: true
decapod_flow_source: "https://github.com/openinfradev/decapod-flow.git"
decapod_flow_dest: "/tmp/decapod_flow"
decapod_flow_version: "master"

helm_operator_version: "v1.1.0"
helm_operator_image_repo: "docker.io/fluxcd/helm-operator"
helm_operator_source: "https://github.com/fluxcd/helm-operator.git"
helm_operator_dest: "/tmp/helm-operator"

argo_version: "v2.9.4"
argo_server_image_repo: "argoproj/argocli"
argo_workflow_controller_image_repo: "argoproj/workflow-controller"
argo_workflow_executor_image_repo: "argoproj/argoexec"
argo_chart_source: "{{ lookup('env', 'HOME') }}/tacoplay/charts/taco-helm/argo"
argo_client_binary_name: "argo-linux-amd64"
argo_client_url: "https://github.com/argoproj/argo/releases/download/{{ argo_version }}/{{ argo_client_binary_name }}"
argo_workflow_archive_enabled: true
argo_archive_storage_size: 8Gi
argo_node_selector: {}
