---
- name: download kubectx binary
  get_url:
    url: "{{ kubectx_download_url }}"
    dest: "{{ artifacts_dir }}/kubectx.tar.gz"
    checksum: "{{ 'sha256:' + kubectx_checksum }}"

- name: download kubens binary
  get_url:
    url: "{{ kubens_download_url }}"
    dest: "{{ artifacts_dir }}/kubens.tar.gz"
    checksum: "{{ 'sha256:' + kubens_checksum }}"
