---
- name: copy helm3 binary to ansible host
  fetch:
    src: "{{ bin_dir }}/helm"
    dest: "{{ artifacts_dir }}/helm3"
    flat: yes
    validate_checksum: no
  become: no
  delegate_to: "{{ groups['kube-master']|first }}"

- name: copy helm3 to bin_dir
  copy:
    src: "{{ artifacts_dir }}/helm3"
    dest: "{{ bin_dir }}/helm3"
    mode: 0755
