---
- name: unarchive kubectx.tar.gz
  unarchive:
    src: "{{ artifacts_dir }}/kubectx.tar.gz"
    dest: "{{ artifacts_dir }}"

- name: copy kubectx to bin_dir
  copy:
    src: "{{ artifacts_dir }}/kubectx"
    dest: "{{ bin_dir }}/kubectx"
    mode: 0755
