---
- name: unarchive kubens.tar.gz
  unarchive:
    src: "{{ artifacts_dir }}/kubens.tar.gz"
    dest: "{{ artifacts_dir }}"

- name: copy kubens to bin_dir
  copy:
    src: "{{ artifacts_dir }}/kubens"
    dest: "{{ bin_dir }}/kubens"
    mode: 0755
