---
- name: copy kube-ps1.sh into /etc/profile.d
  become: yes
  copy:
    src: "{{ artifacts_dir }}/kube-ps1.sh"
    dest: /etc/profile.d/kube-ps1.sh
    mode: 644

- name: check whether .bashrc contains PS1
  command: grep -Frn "PS1='$(kube_ps1)[\u@\h \W]\$ '" {{ lookup('env','HOME') }}/.bashrc
  register: checkps1
  ignore_errors: True
  changed_when: False

- name: add PS1 into basrc
  lineinfile:
    dest: "{{ lookup('env','HOME') }}/.bashrc"
    state: present
    line: "PS1='$(kube_ps1)[\\u@\\h \\W]\\$ '"
  when: not checkps1.rc == 0

- name: source bashrc
  become: no
  shell: source {{ lookup('env','HOME') }}/.bashrc
  args:
    executable: /bin/bash
