---

### ironic service type
ironic_release: stein
run_ironic_container: false
json_rpc_enabled: true

### DHCP Configuration
dhcp_interfaces: ens786f0
dhcp_server: 192.168.48.11
dhcp_subnet: 192.168.48.0
dhcp_netmask: 255.255.255.0

### Node Configuration
ironic_server: 192.168.48.11
ironic_hardware_types: ipmi
ironic_boot_interfaces: pxe
deploy_kernel: "ubuntu-deploy/ubuntu-deploy.kernel"
deploy_ramdisk:  "ubuntu-deploy/ubuntu-deploy.initramfs"
user_kernel: "ubuntu-bionic-user/ubuntu-bionic-image.vmlinuz"
user_ramdisk: "ubuntu-bionic-user/ubuntu-bionic-image.initrd"
user_image: "ubuntu-bionic-user/ubuntu-bionic-image.qcow2"
user_image_checksum: 79e9529d4558827f9397ec33477d1d81

# Node Information for dynamic enrollment
# key: name, desc: name of node, don't duplicate the name
# key: mac, desc: mac address of interface that requests dhcp ip
# key: ip, desc: ip address of node
# key: driver, desc: ironic driver, only supported pxe_ipmitool, pxe_drac, pxe_ilo
# key: driver_address, desc: address of defined ironic driver
# key: driver_user, desc: username of defined ironic driver
# key: driver_password, desc: password of defined ironic driver
# sample configuration
#ironic_nodes:
#  - name: sample-node
#    mac: '00:11:22:33:44:55'
#    ip: 192.168.0.10
#    driver: pxe_ipmitool
#    driver_address: 192.168.100.10
#    driver_user: root
#    driver_password: root

### baremetal image directory
baremetal_image_dir: baremetal-images
ironic_container_dir: "{{ baremetal_image_dir }}/ironic-container"
ironic_image_dir: "{{ baremetal_image_dir }}/ironic-image"

### container file
ironic_api_container_file: ironic-api-pike.tar
ironic_conductor_container_file: ironic-conductor-pike.tar
ironic_base_container_file: ironic-base-pike.tar

### container image name
ironic_base_container_image: kolla/centos-source-ironic-base:5.0.5
ironic_api_container_image:  kolla/centos-source-ironic-api:5.0.5
ironic_conductor_container_image: kolla/centos-source-ironic-conductor:5.0.5
