---

localrepo_enabled: false

### DHCP Configuration
dhcp_interfaces: ens786f0
dhcp_server: 192.168.48.11
dhcp_subnet: 192.168.48.0
dhcp_netmask: 255.255.255.0

### Node Configuration
ironic_server: 192.168.48.11
ironic_driver: pxe_ipmitool
deploy_kernel: ubuntu-deploy.kernel
deploy_ramdisk:  ubuntu-deploy.initramfs
user_kernel: user-centos7.kernel
user_ramdisk: user-centos7.initramfs
user_image: user-centos7.qcow2
user_image_checksum: 1628706adac12fe4a1298f19489cce68

ironic_nodes:
  - name: tp12
    mac: '00:11:0a:67:4e:d8'
    ip: 192.168.48.12
    ipmi_address: 192.168.148.12
    ipmi_user: admin
    ipmi_password: admin
  - name: tp13
    mac: '00:11:0a:67:4e:d9'
    ip: 192.168.48.13
    ipmi_address: 192.168.148.13
    ipmi_user: admin
    ipmi_password: admin
  - name: tp14
    mac: '00:11:0a:67:4e:d0'
    ip: 192.168.48.14
    ipmi_address: 192.168.148.14
    ipmi_user: admin
    ipmi_password: admin

### container file
ironic_api_container_file: ironic-api-pike.tar
ironic_conductor_container_file: ironic-conductor-pike.tar
ironic_base_container_file: ironic-base-pike.tar

### container image name
ironic_base_container_image: kolla/centos-source-ironic-base:5.0.5
ironic_api_container_image:  kolla/centos-source-ironic-api:5.0.5
ironic_conductor_container_image: kolla/centos-source-ironic-conductor:5.0.5

