---
- name: backup current repository files
  import_tasks: backup_repo_files.yml
  when:
      pkg_repo_url != ""
  ignore_errors: yes

- name: set local repo urls
  import_tasks: set_repo_urls.yml
  when:
    - pkg_repo_url != "" or pip_repo_url != ""

- name: add local centos base repo
  template:
    src: local-centosbase.repo.j2
    dest: /etc/yum.repos.d/local-centosbase.repo
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add epel repo
  template:
    src: local-epel.repo.j2
    dest: /etc/yum.repos.d/local-epel.repo
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add docker repo
  template:
    src: local-docker.repo.j2
    dest: /etc/yum.repos.d/local-docker.repo
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["CentOS","RedHat"]

- name: add local ubuntu repo
  template:
    src: local-sources.list.j2
    dest: /etc/apt/sources.list
  when:
    - pkg_repo_url != ""
    - ansible_distribution in ["Ubuntu","Debian"]

- name: set ceph_custom_repo for ceph-ansible
  set_fact:
    ceph_custom_repo: "http://{{ ceph_repo_url }}/ceph/ceph.repo"
  when:
    - ansible_distribution in ["CentOS", "RedHat"]
    - ceph_repo_url != ""

- name: set ceph_custom_repo for ceph-ansible
  set_fact:
    ceph_custom_repo: "http://{{ ceph_repo_url }}/ceph/debian-nautilus"
  when:
    - ceph_repo_url != ""
    - ansible_distribution in ["Ubuntu", "Debian"]

- name: configure debian/ubuntu ceph stable repository key
  apt_key:
    data: "{{ lookup('file', playbook_dir+'/ceph-ansible/roles/ceph-common/files/cephstable.asc') }}"
    state: present
  register: result
  until: result is succeeded
  when:
    - ceph_repo_url != ""
    - ansible_distribution in ["Ubuntu", "Debian"]

- name: add local pypi repo
  template:
    src: pip.conf.j2
    dest: /etc/pip.conf
  when: pip_repo_url != ""

- name: update yum repository cache
  yum:
    update_cache: yes
  when:
    - ansible_distribution in ["CentOS","RedHat"]

- name: update apt repository cache
  apt:
    update_cache: yes
  when:
    - ansible_distribution in ["Ubuntu", "Debian"]
